[package]
name = "sqlite"
version = "0.1.0"
authors = ["shubhamkumar13 <kumar.shubham1312@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion="*"
rustyline="*"
serde="*"